version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    container_name: project_gcs_web
    volumes:
      - web:/usr/src/app/
    ports:
      - ${EXPOSE_PORT}
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASWWORD=${DATABASE_PASWWORD}
      - DATABASE_SSLMODE=${DATABASE_SSLMODE}
    stdin_open: true
    tty: true

volumes:
  web:
    