default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3




pg_default: &pg_default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("DATABASE_HOST") { '0.0.0.0' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '123456789' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'postgres' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { '5432' } %>
  sslmode: 'require'

staging:
  <<: *pg_default
  database: projeto_gcs_staging

production:
  <<: *pg_default
  database: projeto_gcs_production
