name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '2.7.2' ]
        node-version: [ '14' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Webpack compilation
      run: NODE_ENV=test bundle exec rails webpacker:compile

    - name: Run tests
      run: bundle exec rake

    # - name: Run Code Analyzer
    #   run: bundle exec rubocop

    - name: Run check Security Vulnerabilities
      run: bundle exec brakeman
