name: Production

on:
  push:
    branches: [ production ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        build-args: |
          ENVIRONMENT=production
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
        push: true
        tags: eltonlk/projeto-gcs:latest,eltonlk/projeto-gcs:${{ github.sha }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          docker stop projeto-gcs-production
          docker rm projeto-gcs-production
          docker pull eltonlk/projeto-gcs:latest
          docker run --name projeto-gcs-production -e PORT=80 -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} -e DATABASE_USER=${{ secrets.DATABASE_USER }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} -p 80:80 -d eltonlk/projeto-gcs:latest
