name: Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        build-args: |
          ENVIRONMENT=staging
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
        push: true
        tags: eltonlk/projeto-gcs:staging


#tags: eltonlk/projeto-gcs:latest,eltonlk/projeto-gcs:${{ github.sha }}




# docker pull eltonlk/projeto-gcs:latest

# docker run --name projeto-gcs -p 8001:8080 -d eltonlk/projeto-gcs:latest


#docker build -t projeto-gcs --build-arg ENVIRONMENT=staging --build-arg RAILS_MASTER_KEY=cdc4376fcb0b7b5dced7277a92a97428 .



# docker rm projeto-gcs-staging

# ******** docker rmi eltonlk/projeto-gcs:staging

# docker pull eltonlk/projeto-gcs:staging

# docker run --name projeto-gcs-staging --net=host -e PORT=8080 -e DATABASE_HOST=localhost -e DATABASE_USER=univates -e DATABASE_PASSWORD=123456789 -d eltonlk/projeto-gcs:staging
