name: Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        build-args: |
          ENVIRONMENT=staging
          PORT=8080
        push: true
        # tags: eltonlk/projeto-gcs:latest
        repository: eltonlk/projeto-gcs
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true
