name: Staging

on:
  push:
    branches: [ staging ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        build-args: |
          ENVIRONMENT=staging
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
        push: true
        tags: eltonlk/projeto-gcs:staging

  deploy:
    runs-on: ubuntu-latest
    # needs: docker

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSHKEY }}
        port: 22
        script: |
          docker stop projeto-gcs-staging
          docker rm projeto-gcs-staging
          docker pull eltonlk/projeto-gcs:staging
          docker run --name projeto-gcs-staging --net=host -e PORT=8080 -e DATABASE_HOST=localhost -e DATABASE_USER=univates -e DATABASE_PASSWORD=123456789 -d eltonlk/projeto-gcs:staging
