name: Staging

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        build-args: |
          ENVIRONMENT=staging
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
        push: true
        tags: eltonlk/projeto-gcs:staging


#tags: eltonlk/projeto-gcs:${{ github.sha }}


# deploy:

# docker pull eltonlk/projeto-gcs:latest

# docker run --name projeto-gcs -p 8001:8080 -d eltonlk/projeto-gcs:latest


#docker build -t projeto-gcs .

#docker run --name projeto-gcs-staging -e RAILS_ENV=staging -e RAILS_MASTER_KEY=cdc4376fcb0b7b5dced7277a92a97428 -e PORT=3000 -p 3000:3000 -t projeto-gcs



# docker rm projeto-gcs-staging

# docker rmi eltonlk/projeto-gcs:staging

# docker pull eltonlk/projeto-gcs:staging

# docker run --name projeto-gcs-staging --add-host="localhost:192.168.0.1" -e DATABASE_HOST=192.168.0.1 -e DATABASE_USER=postgres -e DATABASE_PASSWORD=123456789 -p 80:3000 -t eltonlk/projeto-gcs:staging
